// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPOyhYY-yDRpbGn61pYCb6l4SaCEq-pc',
    appId: '1:100131328944:web:ed48e9546c4d031bdf7c75',
    messagingSenderId: '100131328944',
    projectId: 'betna-real-estate',
    authDomain: 'betna-real-estate.firebaseapp.com',
    storageBucket: 'betna-real-estate.firebasestorage.app',
    measurementId: 'G-FHSFPF2S42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxSHqSQNlnHb_39mj7Y34NFAbXuFVc0k',
    appId: '1:100131328944:android:73ac317951ac3d96df7c75',
    messagingSenderId: '100131328944',
    projectId: 'betna-real-estate',
    storageBucket: 'betna-real-estate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJTLBQOZT3-9mN52lGGsMXyvpbT0mCDU',
    appId: '1:100131328944:ios:11f76bf5d6eabd86df7c75',
    messagingSenderId: '100131328944',
    projectId: 'betna-real-estate',
    storageBucket: 'betna-real-estate.firebasestorage.app',
    iosBundleId: 'com.betna.tr.betna',
  );
}
