// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn692XrDLvHnjeMPZ8rRC91s86CsHM7og',
    appId: '1:812606330872:web:bad3091fef5afbdeea280d',
    messagingSenderId: '812606330872',
    projectId: 'kira-contract',
    authDomain: 'kira-contract.firebaseapp.com',
    databaseURL: 'https://kira-contract.firebaseio.com',
    storageBucket: 'kira-contract.appspot.com',
    measurementId: 'G-8LLX1BE868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1HDbNCZV3S0k5Dm7iHy7vtGU2kTtW8A',
    appId: '1:812606330872:android:4f860f519ddbd174ea280d',
    messagingSenderId: '812606330872',
    projectId: 'kira-contract',
    databaseURL: 'https://kira-contract.firebaseio.com',
    storageBucket: 'kira-contract.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQWgM_Y-B5Ic1LafvCVInWGez5P4dNRI',
    appId: '1:812606330872:ios:25167eb9f831298eea280d',
    messagingSenderId: '812606330872',
    projectId: 'kira-contract',
    databaseURL: 'https://kira-contract.firebaseio.com',
    storageBucket: 'kira-contract.appspot.com',
    androidClientId: '812606330872-kap6jtsstvi975gash1rru7bo22q5bvq.apps.googleusercontent.com',
    iosClientId: '812606330872-4l6s16asesps9oemg15j8522128ka6cs.apps.googleusercontent.com',
    iosBundleId: 'com.betna.tr.betna',
  );
}
